### ISSUE TITLE
Image from folder, generate stacktrace

### ISSUE THREAD

**Issue by DameniMilo** [DameniMilo/blueimp-gallery#1]
In some cases image from folder seems to generate the following stacktrace:

```
The previous error:  occured 3 times.


Your Server has generated an error. Please review the details below for additional information: 


Error: org.jahia.services.render.RenderException: javax.servlet.jsp.JspTagException: In URL tags, when the "context" attribute is specified, values of both "context" and "url" must start with "/".


Stack trace:
-------------
Cause level : 0 (level 0 is the most precise exception)
javax.servlet.jsp.JspTagException: In URL tags, when the "context" attribute is specified, values of both "context" and "url" must start with "/".
    at org.apache.taglibs.standard.tag.common.core.UrlSupport.resolveUrl(UrlSupport.java:190)
    at org.apache.taglibs.standard.tag.common.core.UrlSupport.doEndTag(UrlSupport.java:141)
    at org.apache.jsp.blueimpnt_005fcarouselImageFromFolder.html.carouselImageFromFolder_jsp._jspx_meth_c_url_1(org.apache.jsp.blueimpnt_005fcarouselImageFromFolder.html.carouselImageFromFolder_jsp:179)
    at org.apache.jsp.blueimpnt_005fcarouselImageFromFolder.html.carouselImageFromFolder_jsp._jspx_meth_c_forEach_0(org.apache.jsp.blueimpnt_005fcarouselImageFromFolder.html.carouselImageFromFolder_jsp:124)
    at org.apache.jsp.blueimpnt_005fcarouselImageFromFolder.html.carouselImageFromFolder_jsp._jspService(org.apache.jsp.blueimpnt_005fcarouselImageFromFolder.html.carouselImageFromFolder_jsp:68)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:384)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:143)
    at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:140)
    at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
    at org.jahia.bundles.extender.jahiamodules.JspServletWrapper.service(JspServletWrapper.java:139)
    at org.apache.felix.http.base.internal.handler.ServletHandler.handleInclude(ServletHandler.java:193)
    at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:148)
    at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:69)
    at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
    at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
    at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
    at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
    at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.felix.http.proxy.ProxyServlet.service(ProxyServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584)
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523)
    at org.jahia.services.render.scripting.RequestDispatcherScript.execute(RequestDispatcherScript.java:126)
    at org.jahia.services.render.filter.TemplateScriptFilter.prepare(TemplateScriptFilter.java:125)
    at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:156)
    at org.jahia.services.render.RenderService.render(RenderService.java:191)
    at org.jahia.taglibs.template.include.ModuleTag.render(ModuleTag.java:623)
    at org.jahia.taglibs.template.include.ModuleTag.doEndTag(ModuleTag.java:314)
...
```

**Comment by DameniMilo** [comment]
Fixed in latest release v1.2
